// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stg_levelset.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace STG {

  /// <summary>Holder for reflection information generated from stg_levelset.proto</summary>
  public static partial class StgLevelsetReflection {

    #region Descriptor
    /// <summary>File descriptor for stg_levelset.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StgLevelsetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzdGdfbGV2ZWxzZXQucHJvdG8SEnN0Z19sZXZlbHNldF9wcm90byJVCghM",
            "ZXZlbHNldBINCgV0aXRsZRgBIAEoCRIpCgZsZXZlbHMYAiADKAsyGS5zdGdf",
            "bGV2ZWxzZXRfcHJvdG8uTGV2ZWwSDwoHYXV0aG9ycxgDIAMoCSLOAQoFTGV2",
            "ZWwSDQoFdGl0bGUYASABKAkSDwoHYXV0aG9ycxgCIAMoCRIOCgZzaXplX3gY",
            "AyABKAUSDgoGc2l6ZV95GAQgASgFEg4KBnNpemVfehgFIAEoBRIvCgNtYXAY",
            "CCADKAsyIi5zdGdfbGV2ZWxzZXRfcHJvdG8uTGV2ZWwuTWFwRW50cnkaRAoI",
            "TWFwRW50cnkSCwoDa2V5GAEgASgFEicKBXZhbHVlGAIgASgLMhguc3RnX2xl",
            "dmVsc2V0X3Byb3RvLkNlbGw6AjgBIpoDCgRDZWxsEiwKB3RlcnJhaW4YASAB",
            "KAsyGy5zdGdfbGV2ZWxzZXRfcHJvdG8uRWxlbWVudBI1ChB0ZXJyYWluX21v",
            "ZGlmaWVyGAIgASgLMhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQSKwoG",
            "cGlja3VwGAMgASgLMhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQSKAoD",
            "bW9iGAQgASgLMhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQSKAoDdG9w",
            "GAUgASgLMhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQSKgoFbm9ydGgY",
            "BiABKAsyGy5zdGdfbGV2ZWxzZXRfcHJvdG8uRWxlbWVudBIpCgRlYXN0GAcg",
            "ASgLMhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQSKgoFc291dGgYCCAB",
            "KAsyGy5zdGdfbGV2ZWxzZXRfcHJvdG8uRWxlbWVudBIpCgR3ZXN0GAkgASgL",
            "Mhsuc3RnX2xldmVsc2V0X3Byb3RvLkVsZW1lbnQi+gEKB0VsZW1lbnQSJgoC",
            "aWQYASABKA4yGi5zdGdfbGV2ZWxzZXRfcHJvdG8uRWxlbUlkEgwKBHJ1bGUY",
            "AiABKAUSDwoHY2hhbm5lbBgDIAEoBRIoCgVjb2xvchgEIAEoDjIZLnN0Z19s",
            "ZXZlbHNldF9wcm90by5Db2xvchIqCgNkaXIYBSABKA4yHS5zdGdfbGV2ZWxz",
            "ZXRfcHJvdG8uRGlyZWN0aW9uEg0KBWNvdW50GAYgASgFEi4KCWludmVudG9y",
            "eRgHIAMoCzIbLnN0Z19sZXZlbHNldF9wcm90by5FbGVtZW50EhMKC3N0cmlu",
            "Z19hcmdzGAggAygJInkKBUlucHV0Ei4KB3ByaW1hcnkYASABKA4yHS5zdGdf",
            "bGV2ZWxzZXRfcHJvdG8uRGlyZWN0aW9uEjAKCXNlY29uZGFyeRgCIAEoDjId",
            "LnN0Z19sZXZlbHNldF9wcm90by5EaXJlY3Rpb24SDgoGYWN0aW9uGAMgASgF",
            "KukECgZFbGVtSWQSFAoQRUxFTUlEX1VOREVGSU5FRBAAEgkKBVNQQUNFEAES",
            "CQoFRkxPT1IQAhIICgRXQUxMEAMSCAoERVhJVBAEEgkKBVdBVEVSEAUSCAoE",
            "RklSRRAGEggKBERJUlQQBxIKCgZHUkFWRUwQCBIHCgNJQ0UQCRIJCgVGT1JD",
            "RRAKEgoKBkNMT05FUhALEggKBEhJTlQQDBIOCgpDSEVDS1BPSU5UEA0SCQoF",
            "VEhJRUYQDhIMCghURUxFUE9SVBAPEggKBFRSQVAQEBIICgRET09SEBESDwoL",
            "VE9HR0xFX1dBTEwQEhIOCgpQT1BVUF9XQUxMEBMSCQoFUEFORUwQZBIQCgxU",
            "T0dHTEVfUEFORUwQZRIRCg1PTkVfV0FZX1BBTkVMEGYSDwoLUE9QVVBfUEFO",
            "RUwQZxIKCgZDT1JORVIQaBILCgZTT0NLRVQQyAESEgoNVE9HR0xFX0JVVFRP",
            "ThDJARITCg5IT0xET05FX0JVVFRPThDKARITCg5IT0xEQUxMX0JVVFRPThDL",
            "ARIRCgxPTkVPRl9CVVRUT04QzAESEAoLQVJFQV9CVVRUT04QzQESCQoEQ0hJ",
            "UBCsAhIJCgRCT01CEK0CEg0KCEZMSVBQRVJTEK4CEgwKB1NVQ1RJT04QrwIS",
            "DgoJRklSRUJPT1RTELACEgsKBlNLQVRFUxCxAhIICgNLRVkQsgISCwoGUExB",
            "WUVSEJADEg8KCkRJUlRfQkxPQ0sQkQMSDAoHTU9OU1RFUhCSAxIJCgRUQU5L",
            "EJMDEhEKDE1PQl9GT0xMT1dFUhDzAxILCgZDQU5PUFkQ9AMqQQoJR2FtZXN0",
            "YXRlEhcKE0dBTUVTVEFURV9VTkRFRklORUQQABIICgRQTEFZEAESCAoETE9T",
            "RRACEgcKA1dJThADKnQKBUNvbG9yEhMKD0NPTE9SX1VOREVGSU5FRBAAEgcK",
            "A1JFRBABEggKBEJMVUUQAhIJCgVHUkVFThADEgoKBllFTExPVxAEEggKBENZ",
            "QU4QBRILCgdNQUdFTlRBEAYSCgoGT1JBTkdFEAcSCQoFQlJPV04QCCpsCglE",
            "aXJlY3Rpb24SFwoTRElSRUNUSU9OX1VOREVGSU5FRBAAEgUKAU4QARIFCgFF",
            "EAISBQoBUxADEgUKAVcQBBIGCgJORRAFEgYKAlNFEAYSBgoCU1cQBxIGCgJO",
            "VxAIEgoKBlJBTkRPTRAJQgaqAgNTVEdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::STG.ElemId), typeof(global::STG.Gamestate), typeof(global::STG.Color), typeof(global::STG.Direction), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Levelset), global::STG.Levelset.Parser, new[]{ "Title", "Levels", "Authors" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Level), global::STG.Level.Parser, new[]{ "Title", "Authors", "SizeX", "SizeY", "SizeZ", "Map" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Cell), global::STG.Cell.Parser, new[]{ "Terrain", "TerrainModifier", "Pickup", "Mob", "Top", "North", "East", "South", "West" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Element), global::STG.Element.Parser, new[]{ "Id", "Rule", "Channel", "Color", "Dir", "Count", "Inventory", "StringArgs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Input), global::STG.Input.Parser, new[]{ "Primary", "Secondary", "Action" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ElemId {
    [pbr::OriginalName("ELEMID_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// TERRAIN
    /// </summary>
    [pbr::OriginalName("SPACE")] Space = 1,
    /// <summary>
    /// color
    /// </summary>
    [pbr::OriginalName("FLOOR")] Floor = 2,
    /// <summary>
    /// rule (0 = NORMAL, 1 = APPEARING, 2 = INVISIBLE, 3 = BLUE REAL, 4 = BLUE FAKE)
    /// </summary>
    [pbr::OriginalName("WALL")] Wall = 3,
    /// <summary>
    /// color, count = timelimit
    /// </summary>
    [pbr::OriginalName("EXIT")] Exit = 4,
    /// <summary>
    /// color (for dirt/floor that appears when filled in)
    /// </summary>
    [pbr::OriginalName("WATER")] Water = 5,
    /// <summary>
    /// color (for water that appears when filled in)
    /// </summary>
    [pbr::OriginalName("FIRE")] Fire = 6,
    /// <summary>
    /// color (for floor that appears)
    /// </summary>
    [pbr::OriginalName("DIRT")] Dirt = 7,
    [pbr::OriginalName("GRAVEL")] Gravel = 8,
    [pbr::OriginalName("ICE")] Ice = 9,
    /// <summary>
    /// color, direction (0 = RAND, 1 = N, 2 = E, 3 = S, 4 = W)
    /// </summary>
    [pbr::OriginalName("FORCE")] Force = 10,
    /// <summary>
    /// color
    /// </summary>
    [pbr::OriginalName("CLONER")] Cloner = 11,
    [pbr::OriginalName("HINT")] Hint = 12,
    [pbr::OriginalName("CHECKPOINT")] Checkpoint = 13,
    /// <summary>
    /// rule (0 = item, 1 = key)
    /// </summary>
    [pbr::OriginalName("THIEF")] Thief = 14,
    /// <summary>
    /// color
    /// </summary>
    [pbr::OriginalName("TELEPORT")] Teleport = 15,
    /// <summary>
    /// color, rule (0 = OPEN, 1 = SHUT)
    /// </summary>
    [pbr::OriginalName("TRAP")] Trap = 16,
    /// <summary>
    /// color
    /// </summary>
    [pbr::OriginalName("DOOR")] Door = 17,
    /// <summary>
    /// color, rule (0 = OPEN, 1 = SHUT)
    /// </summary>
    [pbr::OriginalName("TOGGLE_WALL")] ToggleWall = 18,
    /// <summary>
    /// color, count
    /// </summary>
    [pbr::OriginalName("POPUP_WALL")] PopupWall = 19,
    /// <summary>
    /// NESW
    /// </summary>
    [pbr::OriginalName("PANEL")] Panel = 100,
    /// <summary>
    /// color, rule (0 = OPEN, 1 = SHUT)
    /// </summary>
    [pbr::OriginalName("TOGGLE_PANEL")] TogglePanel = 101,
    /// <summary>
    /// color, rule (0 = IN, 1 = OUT)
    /// </summary>
    [pbr::OriginalName("ONE_WAY_PANEL")] OneWayPanel = 102,
    /// <summary>
    /// color, count
    /// </summary>
    [pbr::OriginalName("POPUP_PANEL")] PopupPanel = 103,
    /// <summary>
    /// Modifies exit direction. Use on ice for ice corners.
    /// Also useful on floors and force floors.
    /// </summary>
    [pbr::OriginalName("CORNER")] Corner = 104,
    /// <summary>
    /// TERRAIN_MODIFIER
    /// </summary>
    [pbr::OriginalName("SOCKET")] Socket = 200,
    /// <summary>
    /// TOGGLE: Toggle event for {color, channel} when pressed. (default for TW cloners, tanks, toggles).
    /// HOLDONE: (default for TW traps)
    ///      Toggle event when the first HOLDONE button of this {color, channel} is pressed.
    ///      Toggle event when the last HOLDONE button of this {color, channel} is released.
    /// HOLDALL
    ///      Toggle event when the last HOLDALL button of this {color, channel} is pressed.
    ///      Toggle event when the first HOLDALL buttonn of this {color, channel} is released.
    /// ONEOF
    ///      Set this {color, channel} to True.
    ///      For this {color}, set all other channels to False.
    /// AREA
    ///      Same as toggle but only acts on elements in a 5x5 square.
    /// </summary>
    [pbr::OriginalName("TOGGLE_BUTTON")] ToggleButton = 201,
    /// <summary>
    /// + color, channel
    /// </summary>
    [pbr::OriginalName("HOLDONE_BUTTON")] HoldoneButton = 202,
    /// <summary>
    /// + color, channel
    /// </summary>
    [pbr::OriginalName("HOLDALL_BUTTON")] HoldallButton = 203,
    /// <summary>
    /// + color, channel
    /// </summary>
    [pbr::OriginalName("ONEOF_BUTTON")] OneofButton = 204,
    /// <summary>
    /// + color, channel
    /// </summary>
    [pbr::OriginalName("AREA_BUTTON")] AreaButton = 205,
    /// <summary>
    /// PICKUP
    /// Rule: 
    /// --NORMAL: mobs can enter but cannot pickup
    /// --RAINBOW_FENCE: mobs can pickup and use
    /// --FENCE: mobs cannot enter
    /// </summary>
    [pbr::OriginalName("CHIP")] Chip = 300,
    [pbr::OriginalName("BOMB")] Bomb = 301,
    /// <summary>
    /// rule, count
    /// </summary>
    [pbr::OriginalName("FLIPPERS")] Flippers = 302,
    /// <summary>
    /// rule, count
    /// </summary>
    [pbr::OriginalName("SUCTION")] Suction = 303,
    /// <summary>
    /// rule, count
    /// </summary>
    [pbr::OriginalName("FIREBOOTS")] Fireboots = 304,
    /// <summary>
    /// rule, count
    /// </summary>
    [pbr::OriginalName("SKATES")] Skates = 305,
    /// <summary>
    /// color, rule, count (999 = FOREVER KEY, do not decrement)
    /// </summary>
    [pbr::OriginalName("KEY")] Key = 306,
    /// <summary>
    /// MOB
    /// </summary>
    [pbr::OriginalName("PLAYER")] Player = 400,
    /// <summary>
    /// dir, inv
    /// </summary>
    [pbr::OriginalName("DIRT_BLOCK")] DirtBlock = 401,
    /// <summary>
    /// 1 ANT 2 PARA 3 GLIDER 4 FIREBALL 5 BALL 6 WALKER 7 BLOB 8 TEETH
    /// </summary>
    [pbr::OriginalName("MONSTER")] Monster = 402,
    /// <summary>
    /// color, dir
    /// </summary>
    [pbr::OriginalName("TANK")] Tank = 403,
    /// <summary>
    /// Invisible token that blocks mob entry until next tick.
    /// Ensures well behaved monster patterns.
    /// </summary>
    [pbr::OriginalName("MOB_FOLLOWER")] MobFollower = 499,
    /// <summary>
    /// TOP
    /// </summary>
    [pbr::OriginalName("CANOPY")] Canopy = 500,
  }

  public enum Gamestate {
    [pbr::OriginalName("GAMESTATE_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("PLAY")] Play = 1,
    [pbr::OriginalName("LOSE")] Lose = 2,
    [pbr::OriginalName("WIN")] Win = 3,
  }

  public enum Color {
    [pbr::OriginalName("COLOR_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("RED")] Red = 1,
    [pbr::OriginalName("BLUE")] Blue = 2,
    [pbr::OriginalName("GREEN")] Green = 3,
    [pbr::OriginalName("YELLOW")] Yellow = 4,
    [pbr::OriginalName("CYAN")] Cyan = 5,
    [pbr::OriginalName("MAGENTA")] Magenta = 6,
    [pbr::OriginalName("ORANGE")] Orange = 7,
    [pbr::OriginalName("BROWN")] Brown = 8,
  }

  public enum Direction {
    [pbr::OriginalName("DIRECTION_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("N")] N = 1,
    [pbr::OriginalName("E")] E = 2,
    [pbr::OriginalName("S")] S = 3,
    [pbr::OriginalName("W")] W = 4,
    [pbr::OriginalName("NE")] Ne = 5,
    [pbr::OriginalName("SE")] Se = 6,
    [pbr::OriginalName("SW")] Sw = 7,
    [pbr::OriginalName("NW")] Nw = 8,
    [pbr::OriginalName("RANDOM")] Random = 9,
  }

  #endregion

  #region Messages
  public sealed partial class Levelset : pb::IMessage<Levelset>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Levelset> _parser = new pb::MessageParser<Levelset>(() => new Levelset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Levelset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.StgLevelsetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset(Levelset other) : this() {
      title_ = other.title_;
      levels_ = other.levels_.Clone();
      authors_ = other.authors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset Clone() {
      return new Levelset(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::STG.Level> _repeated_levels_codec
        = pb::FieldCodec.ForMessage(18, global::STG.Level.Parser);
    private readonly pbc::RepeatedField<global::STG.Level> levels_ = new pbc::RepeatedField<global::STG.Level>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::STG.Level> Levels {
      get { return levels_; }
    }

    /// <summary>Field number for the "authors" field.</summary>
    public const int AuthorsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_authors_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> authors_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Authors {
      get { return authors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Levelset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Levelset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if(!levels_.Equals(other.levels_)) return false;
      if(!authors_.Equals(other.authors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      hash ^= levels_.GetHashCode();
      hash ^= authors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      levels_.WriteTo(output, _repeated_levels_codec);
      authors_.WriteTo(output, _repeated_authors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      levels_.WriteTo(ref output, _repeated_levels_codec);
      authors_.WriteTo(ref output, _repeated_authors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      size += levels_.CalculateSize(_repeated_levels_codec);
      size += authors_.CalculateSize(_repeated_authors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Levelset other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      levels_.Add(other.levels_);
      authors_.Add(other.authors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(input, _repeated_levels_codec);
            break;
          }
          case 26: {
            authors_.AddEntriesFrom(input, _repeated_authors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(ref input, _repeated_levels_codec);
            break;
          }
          case 26: {
            authors_.AddEntriesFrom(ref input, _repeated_authors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Level : pb::IMessage<Level>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Level> _parser = new pb::MessageParser<Level>(() => new Level());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Level> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.StgLevelsetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level(Level other) : this() {
      title_ = other.title_;
      authors_ = other.authors_.Clone();
      sizeX_ = other.sizeX_;
      sizeY_ = other.sizeY_;
      sizeZ_ = other.sizeZ_;
      map_ = other.map_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level Clone() {
      return new Level(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "authors" field.</summary>
    public const int AuthorsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_authors_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> authors_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Authors {
      get { return authors_; }
    }

    /// <summary>Field number for the "size_x" field.</summary>
    public const int SizeXFieldNumber = 3;
    private int sizeX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeX {
      get { return sizeX_; }
      set {
        sizeX_ = value;
      }
    }

    /// <summary>Field number for the "size_y" field.</summary>
    public const int SizeYFieldNumber = 4;
    private int sizeY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeY {
      get { return sizeY_; }
      set {
        sizeY_ = value;
      }
    }

    /// <summary>Field number for the "size_z" field.</summary>
    public const int SizeZFieldNumber = 5;
    private int sizeZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeZ {
      get { return sizeZ_; }
      set {
        sizeZ_ = value;
      }
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 8;
    private static readonly pbc::MapField<int, global::STG.Cell>.Codec _map_map_codec
        = new pbc::MapField<int, global::STG.Cell>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::STG.Cell.Parser), 66);
    private readonly pbc::MapField<int, global::STG.Cell> map_ = new pbc::MapField<int, global::STG.Cell>();
    /// <summary>
    /// p = z * (size_x + size_y) + y * size_x + x
    /// x = (p % size_z) % size_x
    /// y = (p % size_z) // size_x
    /// z = p // size_z
    /// position to cell containing tokens
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::STG.Cell> Map {
      get { return map_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Level);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Level other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if(!authors_.Equals(other.authors_)) return false;
      if (SizeX != other.SizeX) return false;
      if (SizeY != other.SizeY) return false;
      if (SizeZ != other.SizeZ) return false;
      if (!Map.Equals(other.Map)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      hash ^= authors_.GetHashCode();
      if (SizeX != 0) hash ^= SizeX.GetHashCode();
      if (SizeY != 0) hash ^= SizeY.GetHashCode();
      if (SizeZ != 0) hash ^= SizeZ.GetHashCode();
      hash ^= Map.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      authors_.WriteTo(output, _repeated_authors_codec);
      if (SizeX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SizeX);
      }
      if (SizeY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SizeY);
      }
      if (SizeZ != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SizeZ);
      }
      map_.WriteTo(output, _map_map_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      authors_.WriteTo(ref output, _repeated_authors_codec);
      if (SizeX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SizeX);
      }
      if (SizeY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SizeY);
      }
      if (SizeZ != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SizeZ);
      }
      map_.WriteTo(ref output, _map_map_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      size += authors_.CalculateSize(_repeated_authors_codec);
      if (SizeX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeX);
      }
      if (SizeY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeY);
      }
      if (SizeZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeZ);
      }
      size += map_.CalculateSize(_map_map_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Level other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      authors_.Add(other.authors_);
      if (other.SizeX != 0) {
        SizeX = other.SizeX;
      }
      if (other.SizeY != 0) {
        SizeY = other.SizeY;
      }
      if (other.SizeZ != 0) {
        SizeZ = other.SizeZ;
      }
      map_.Add(other.map_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            authors_.AddEntriesFrom(input, _repeated_authors_codec);
            break;
          }
          case 24: {
            SizeX = input.ReadInt32();
            break;
          }
          case 32: {
            SizeY = input.ReadInt32();
            break;
          }
          case 40: {
            SizeZ = input.ReadInt32();
            break;
          }
          case 66: {
            map_.AddEntriesFrom(input, _map_map_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            authors_.AddEntriesFrom(ref input, _repeated_authors_codec);
            break;
          }
          case 24: {
            SizeX = input.ReadInt32();
            break;
          }
          case 32: {
            SizeY = input.ReadInt32();
            break;
          }
          case 40: {
            SizeZ = input.ReadInt32();
            break;
          }
          case 66: {
            map_.AddEntriesFrom(ref input, _map_map_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Cell : pb::IMessage<Cell>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cell> _parser = new pb::MessageParser<Cell>(() => new Cell());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cell> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.StgLevelsetReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell(Cell other) : this() {
      terrain_ = other.terrain_ != null ? other.terrain_.Clone() : null;
      terrainModifier_ = other.terrainModifier_ != null ? other.terrainModifier_.Clone() : null;
      pickup_ = other.pickup_ != null ? other.pickup_.Clone() : null;
      mob_ = other.mob_ != null ? other.mob_.Clone() : null;
      top_ = other.top_ != null ? other.top_.Clone() : null;
      north_ = other.north_ != null ? other.north_.Clone() : null;
      east_ = other.east_ != null ? other.east_.Clone() : null;
      south_ = other.south_ != null ? other.south_.Clone() : null;
      west_ = other.west_ != null ? other.west_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell Clone() {
      return new Cell(this);
    }

    /// <summary>Field number for the "terrain" field.</summary>
    public const int TerrainFieldNumber = 1;
    private global::STG.Element terrain_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Terrain {
      get { return terrain_; }
      set {
        terrain_ = value;
      }
    }

    /// <summary>Field number for the "terrain_modifier" field.</summary>
    public const int TerrainModifierFieldNumber = 2;
    private global::STG.Element terrainModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element TerrainModifier {
      get { return terrainModifier_; }
      set {
        terrainModifier_ = value;
      }
    }

    /// <summary>Field number for the "pickup" field.</summary>
    public const int PickupFieldNumber = 3;
    private global::STG.Element pickup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Pickup {
      get { return pickup_; }
      set {
        pickup_ = value;
      }
    }

    /// <summary>Field number for the "mob" field.</summary>
    public const int MobFieldNumber = 4;
    private global::STG.Element mob_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Mob {
      get { return mob_; }
      set {
        mob_ = value;
      }
    }

    /// <summary>Field number for the "top" field.</summary>
    public const int TopFieldNumber = 5;
    private global::STG.Element top_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Top {
      get { return top_; }
      set {
        top_ = value;
      }
    }

    /// <summary>Field number for the "north" field.</summary>
    public const int NorthFieldNumber = 6;
    private global::STG.Element north_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element North {
      get { return north_; }
      set {
        north_ = value;
      }
    }

    /// <summary>Field number for the "east" field.</summary>
    public const int EastFieldNumber = 7;
    private global::STG.Element east_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element East {
      get { return east_; }
      set {
        east_ = value;
      }
    }

    /// <summary>Field number for the "south" field.</summary>
    public const int SouthFieldNumber = 8;
    private global::STG.Element south_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element South {
      get { return south_; }
      set {
        south_ = value;
      }
    }

    /// <summary>Field number for the "west" field.</summary>
    public const int WestFieldNumber = 9;
    private global::STG.Element west_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element West {
      get { return west_; }
      set {
        west_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cell);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cell other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Terrain, other.Terrain)) return false;
      if (!object.Equals(TerrainModifier, other.TerrainModifier)) return false;
      if (!object.Equals(Pickup, other.Pickup)) return false;
      if (!object.Equals(Mob, other.Mob)) return false;
      if (!object.Equals(Top, other.Top)) return false;
      if (!object.Equals(North, other.North)) return false;
      if (!object.Equals(East, other.East)) return false;
      if (!object.Equals(South, other.South)) return false;
      if (!object.Equals(West, other.West)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (terrain_ != null) hash ^= Terrain.GetHashCode();
      if (terrainModifier_ != null) hash ^= TerrainModifier.GetHashCode();
      if (pickup_ != null) hash ^= Pickup.GetHashCode();
      if (mob_ != null) hash ^= Mob.GetHashCode();
      if (top_ != null) hash ^= Top.GetHashCode();
      if (north_ != null) hash ^= North.GetHashCode();
      if (east_ != null) hash ^= East.GetHashCode();
      if (south_ != null) hash ^= South.GetHashCode();
      if (west_ != null) hash ^= West.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      if (terrainModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TerrainModifier);
      }
      if (pickup_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pickup);
      }
      if (mob_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Mob);
      }
      if (top_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Top);
      }
      if (north_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(North);
      }
      if (east_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(East);
      }
      if (south_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(South);
      }
      if (west_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(West);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      if (terrainModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TerrainModifier);
      }
      if (pickup_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pickup);
      }
      if (mob_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Mob);
      }
      if (top_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Top);
      }
      if (north_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(North);
      }
      if (east_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(East);
      }
      if (south_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(South);
      }
      if (west_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(West);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (terrain_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Terrain);
      }
      if (terrainModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TerrainModifier);
      }
      if (pickup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pickup);
      }
      if (mob_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mob);
      }
      if (top_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Top);
      }
      if (north_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(North);
      }
      if (east_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(East);
      }
      if (south_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(South);
      }
      if (west_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(West);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cell other) {
      if (other == null) {
        return;
      }
      if (other.terrain_ != null) {
        if (terrain_ == null) {
          Terrain = new global::STG.Element();
        }
        Terrain.MergeFrom(other.Terrain);
      }
      if (other.terrainModifier_ != null) {
        if (terrainModifier_ == null) {
          TerrainModifier = new global::STG.Element();
        }
        TerrainModifier.MergeFrom(other.TerrainModifier);
      }
      if (other.pickup_ != null) {
        if (pickup_ == null) {
          Pickup = new global::STG.Element();
        }
        Pickup.MergeFrom(other.Pickup);
      }
      if (other.mob_ != null) {
        if (mob_ == null) {
          Mob = new global::STG.Element();
        }
        Mob.MergeFrom(other.Mob);
      }
      if (other.top_ != null) {
        if (top_ == null) {
          Top = new global::STG.Element();
        }
        Top.MergeFrom(other.Top);
      }
      if (other.north_ != null) {
        if (north_ == null) {
          North = new global::STG.Element();
        }
        North.MergeFrom(other.North);
      }
      if (other.east_ != null) {
        if (east_ == null) {
          East = new global::STG.Element();
        }
        East.MergeFrom(other.East);
      }
      if (other.south_ != null) {
        if (south_ == null) {
          South = new global::STG.Element();
        }
        South.MergeFrom(other.South);
      }
      if (other.west_ != null) {
        if (west_ == null) {
          West = new global::STG.Element();
        }
        West.MergeFrom(other.West);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::STG.Element();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 18: {
            if (terrainModifier_ == null) {
              TerrainModifier = new global::STG.Element();
            }
            input.ReadMessage(TerrainModifier);
            break;
          }
          case 26: {
            if (pickup_ == null) {
              Pickup = new global::STG.Element();
            }
            input.ReadMessage(Pickup);
            break;
          }
          case 34: {
            if (mob_ == null) {
              Mob = new global::STG.Element();
            }
            input.ReadMessage(Mob);
            break;
          }
          case 42: {
            if (top_ == null) {
              Top = new global::STG.Element();
            }
            input.ReadMessage(Top);
            break;
          }
          case 50: {
            if (north_ == null) {
              North = new global::STG.Element();
            }
            input.ReadMessage(North);
            break;
          }
          case 58: {
            if (east_ == null) {
              East = new global::STG.Element();
            }
            input.ReadMessage(East);
            break;
          }
          case 66: {
            if (south_ == null) {
              South = new global::STG.Element();
            }
            input.ReadMessage(South);
            break;
          }
          case 74: {
            if (west_ == null) {
              West = new global::STG.Element();
            }
            input.ReadMessage(West);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::STG.Element();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 18: {
            if (terrainModifier_ == null) {
              TerrainModifier = new global::STG.Element();
            }
            input.ReadMessage(TerrainModifier);
            break;
          }
          case 26: {
            if (pickup_ == null) {
              Pickup = new global::STG.Element();
            }
            input.ReadMessage(Pickup);
            break;
          }
          case 34: {
            if (mob_ == null) {
              Mob = new global::STG.Element();
            }
            input.ReadMessage(Mob);
            break;
          }
          case 42: {
            if (top_ == null) {
              Top = new global::STG.Element();
            }
            input.ReadMessage(Top);
            break;
          }
          case 50: {
            if (north_ == null) {
              North = new global::STG.Element();
            }
            input.ReadMessage(North);
            break;
          }
          case 58: {
            if (east_ == null) {
              East = new global::STG.Element();
            }
            input.ReadMessage(East);
            break;
          }
          case 66: {
            if (south_ == null) {
              South = new global::STG.Element();
            }
            input.ReadMessage(South);
            break;
          }
          case 74: {
            if (west_ == null) {
              West = new global::STG.Element();
            }
            input.ReadMessage(West);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Element : pb::IMessage<Element>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Element> _parser = new pb::MessageParser<Element>(() => new Element());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Element> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.StgLevelsetReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element(Element other) : this() {
      id_ = other.id_;
      rule_ = other.rule_;
      channel_ = other.channel_;
      color_ = other.color_;
      dir_ = other.dir_;
      count_ = other.count_;
      inventory_ = other.inventory_.Clone();
      stringArgs_ = other.stringArgs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element Clone() {
      return new Element(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::STG.ElemId id_ = global::STG.ElemId.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.ElemId Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "rule" field.</summary>
    public const int RuleFieldNumber = 2;
    private int rule_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rule {
      get { return rule_; }
      set {
        rule_ = value;
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 3;
    private int channel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 4;
    private global::STG.Color color_ = global::STG.Color.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "dir" field.</summary>
    public const int DirFieldNumber = 5;
    private global::STG.Direction dir_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Dir {
      get { return dir_; }
      set {
        dir_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 6;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "inventory" field.</summary>
    public const int InventoryFieldNumber = 7;
    private static readonly pb::FieldCodec<global::STG.Element> _repeated_inventory_codec
        = pb::FieldCodec.ForMessage(58, global::STG.Element.Parser);
    private readonly pbc::RepeatedField<global::STG.Element> inventory_ = new pbc::RepeatedField<global::STG.Element>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::STG.Element> Inventory {
      get { return inventory_; }
    }

    /// <summary>Field number for the "string_args" field.</summary>
    public const int StringArgsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_stringArgs_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> stringArgs_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// for hints, messages, maybe checkpoints
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StringArgs {
      get { return stringArgs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Element);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Element other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Rule != other.Rule) return false;
      if (Channel != other.Channel) return false;
      if (Color != other.Color) return false;
      if (Dir != other.Dir) return false;
      if (Count != other.Count) return false;
      if(!inventory_.Equals(other.inventory_)) return false;
      if(!stringArgs_.Equals(other.stringArgs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != global::STG.ElemId.Undefined) hash ^= Id.GetHashCode();
      if (Rule != 0) hash ^= Rule.GetHashCode();
      if (Channel != 0) hash ^= Channel.GetHashCode();
      if (Color != global::STG.Color.Undefined) hash ^= Color.GetHashCode();
      if (Dir != global::STG.Direction.Undefined) hash ^= Dir.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      hash ^= inventory_.GetHashCode();
      hash ^= stringArgs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != global::STG.ElemId.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (Rule != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rule);
      }
      if (Channel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Channel);
      }
      if (Color != global::STG.Color.Undefined) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Color);
      }
      if (Dir != global::STG.Direction.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Dir);
      }
      if (Count != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Count);
      }
      inventory_.WriteTo(output, _repeated_inventory_codec);
      stringArgs_.WriteTo(output, _repeated_stringArgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != global::STG.ElemId.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (Rule != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rule);
      }
      if (Channel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Channel);
      }
      if (Color != global::STG.Color.Undefined) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Color);
      }
      if (Dir != global::STG.Direction.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Dir);
      }
      if (Count != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Count);
      }
      inventory_.WriteTo(ref output, _repeated_inventory_codec);
      stringArgs_.WriteTo(ref output, _repeated_stringArgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != global::STG.ElemId.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id);
      }
      if (Rule != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rule);
      }
      if (Channel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Channel);
      }
      if (Color != global::STG.Color.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Color);
      }
      if (Dir != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Dir);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      size += inventory_.CalculateSize(_repeated_inventory_codec);
      size += stringArgs_.CalculateSize(_repeated_stringArgs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Element other) {
      if (other == null) {
        return;
      }
      if (other.Id != global::STG.ElemId.Undefined) {
        Id = other.Id;
      }
      if (other.Rule != 0) {
        Rule = other.Rule;
      }
      if (other.Channel != 0) {
        Channel = other.Channel;
      }
      if (other.Color != global::STG.Color.Undefined) {
        Color = other.Color;
      }
      if (other.Dir != global::STG.Direction.Undefined) {
        Dir = other.Dir;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      inventory_.Add(other.inventory_);
      stringArgs_.Add(other.stringArgs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = (global::STG.ElemId) input.ReadEnum();
            break;
          }
          case 16: {
            Rule = input.ReadInt32();
            break;
          }
          case 24: {
            Channel = input.ReadInt32();
            break;
          }
          case 32: {
            Color = (global::STG.Color) input.ReadEnum();
            break;
          }
          case 40: {
            Dir = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 48: {
            Count = input.ReadInt32();
            break;
          }
          case 58: {
            inventory_.AddEntriesFrom(input, _repeated_inventory_codec);
            break;
          }
          case 66: {
            stringArgs_.AddEntriesFrom(input, _repeated_stringArgs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = (global::STG.ElemId) input.ReadEnum();
            break;
          }
          case 16: {
            Rule = input.ReadInt32();
            break;
          }
          case 24: {
            Channel = input.ReadInt32();
            break;
          }
          case 32: {
            Color = (global::STG.Color) input.ReadEnum();
            break;
          }
          case 40: {
            Dir = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 48: {
            Count = input.ReadInt32();
            break;
          }
          case 58: {
            inventory_.AddEntriesFrom(ref input, _repeated_inventory_codec);
            break;
          }
          case 66: {
            stringArgs_.AddEntriesFrom(ref input, _repeated_stringArgs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Input : pb::IMessage<Input>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Input> _parser = new pb::MessageParser<Input>(() => new Input());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Input> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.StgLevelsetReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input(Input other) : this() {
      primary_ = other.primary_;
      secondary_ = other.secondary_;
      action_ = other.action_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input Clone() {
      return new Input(this);
    }

    /// <summary>Field number for the "primary" field.</summary>
    public const int PrimaryFieldNumber = 1;
    private global::STG.Direction primary_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Primary {
      get { return primary_; }
      set {
        primary_ = value;
      }
    }

    /// <summary>Field number for the "secondary" field.</summary>
    public const int SecondaryFieldNumber = 2;
    private global::STG.Direction secondary_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Secondary {
      get { return secondary_; }
      set {
        secondary_ = value;
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 3;
    private int action_;
    /// <summary>
    /// 0 indicates no action. Likely limit to 1, 2, or 3.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Input);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Input other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Primary != other.Primary) return false;
      if (Secondary != other.Secondary) return false;
      if (Action != other.Action) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Primary != global::STG.Direction.Undefined) hash ^= Primary.GetHashCode();
      if (Secondary != global::STG.Direction.Undefined) hash ^= Secondary.GetHashCode();
      if (Action != 0) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Primary != global::STG.Direction.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Secondary);
      }
      if (Action != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Primary != global::STG.Direction.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Secondary);
      }
      if (Action != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Primary != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Secondary);
      }
      if (Action != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Input other) {
      if (other == null) {
        return;
      }
      if (other.Primary != global::STG.Direction.Undefined) {
        Primary = other.Primary;
      }
      if (other.Secondary != global::STG.Direction.Undefined) {
        Secondary = other.Secondary;
      }
      if (other.Action != 0) {
        Action = other.Action;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Primary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Secondary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            Action = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Primary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Secondary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            Action = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
